SC-17421 add kube-controller metrics and descriptions
sematext/docs pull request #528
Opened 2023-09-26 09:10 UTC by yago-123

2023-09-26 23:26 UTC, otisg commented on docs/integration/kubernetes.md
> +| kubecontroller.workqueue_wait.p50latency | gauge | seconds | p50 latency of waiting time before item is processed |
latency of waiting time => wait time latency or simply wait latency

2023-09-26 23:30 UTC, otisg requested changes

2023-09-26 23:30 UTC, otisg commented on docs/integration/kubernetes.md
> +|kubecontroller.workqueue_process.total_num| gauge |   | number items being processed by Kube-controller        |
number OF ...

2023-09-26 23:30 UTC, otisg commented on docs/integration/kubernetes.md
> +| kubecontroller.workqueue_wait.p50latency | gauge | seconds | p50 latency of waiting time before item is processed |
latency of waiting time => wait time latency or simply wait latency

2023-09-26 23:30 UTC, otisg commented on docs/integration/kubernetes.md
> +|kubecontroller.workqueue_depth.total_num| gauge |   | number of items pending for being processed |
number of items queued for processing

2023-09-26 23:30 UTC, otisg commented on docs/integration/kubernetes.md
> +|kubecontroller.workqueue_unfinished_work.total_num| gauge |   | number of items remaining unfinished in a workqueue |
number of items remaining in the work queue
or simply
number of items in the work queue

2023-09-26 23:30 UTC, otisg commented on docs/integration/kubernetes.md
> +|kubecontroller.workqueue_longest_running.total_num| gauge |   | number of longest-running task processor within a workqueue |
number of longest-running task processors in work queue

2023-09-26 23:30 UTC, otisg commented on docs/integration/kubernetes.md
> +|kubecontroller.workqueue_unfinished_work.total_num| gauge |   | number of items remaining unfinished in a workqueue |
work queue or workqueue. I assume the former is better.  Just be consistent.

2023-09-26 23:30 UTC, otisg commented on docs/integration/kubernetes.md
> +|kubecontroller.workqueue_retries.total_num| gauge |   | number of retries that have been attempted by workqueue items |
s/that have been//

2023-09-27 10:15 UTC, cpipilas commented on docs/integration/kubernetes.md
> +|kubecontroller.workqueue_process.duration| gauge | seconds | duration of item being processed by Kube-controller    |
>  duration of item being processed by Kube-controller

---> "Duration of processing an item from workqueue"

2023-09-27 16:03 UTC, yago-123 commented
Addressed the comments, GitHub still does not notify about this repo

2023-09-27 16:15 UTC, cpipilas approved these changes
LGTM

2023-09-28 08:22 UTC, merged